import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

import ToasterProvider from "@/providers/Toaster";

const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-stone-950 text-white`}>
        <ToasterProvider />
        {children}
      </body>
    </html>
  );
}
